version: '3'
services:
  eureka:
     image: aista/eureka
     container_name: eureka-intern
     restart: always
     ports:
      - "9761:8761"
  count:
    depends_on: 
      - eureka
    container_name: count_grpc
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile.count.grpc
    entrypoint:
    - /count
    - -g
    - -a
    - count
    - --registrar-url
    - http://eureka:8761/eureka
        
